# A comprehensive list of major US cities and their state abbreviations.
# This list covers the top ~300+ most populous US cities to provide a robust autocomplete experience.

MAJOR_US_CITIES = [
    "New York, NY", "Los Angeles, CA", "Chicago, IL", "Houston, TX", "Phoenix, AZ", "Philadelphia, PA",
    "San Antonio, TX", "San Diego, CA", "Dallas, TX", "San Jose, CA", "Austin, TX", "Jacksonville, FL",
    "Fort Worth, TX", "Columbus, OH", "Indianapolis, IN", "Charlotte, NC", "San Francisco, CA",
    "Seattle, WA", "Denver, CO", "Washington, DC", "Nashville, TN", "Oklahoma City, OK",
    "El Paso, TX", "Boston, MA", "Portland, OR", "Las Vegas, NV", "Detroit, MI", "Memphis, TN",
    "Louisville, KY", "Baltimore, MD", "Milwaukee, WI", "Albuquerque, NM", "Tucson, AZ",
    "Fresno, CA", "Sacramento, CA", "Kansas City, MO", "Mesa, AZ", "Atlanta, GA", "Omaha, NE",
    "Colorado Springs, CO", "Raleigh, NC", "Long Beach, CA", "Virginia Beach, VA", "Miami, FL",
    "Oakland, CA", "Minneapolis, MN", "Tulsa, OK", "Bakersfield, CA", "Wichita, KS", "Arlington, TX",
    "Aurora, CO", "Tampa, FL", "New Orleans, LA", "Cleveland, OH", "Honolulu, HI", "Anaheim, CA",
    "Lexington, KY", "Stockton, CA", "Corpus Christi, TX", "Henderson, NV", "Riverside, CA",
    "Newark, NJ", "St. Paul, MN", "Santa Ana, CA", "Cincinnati, OH", "Irvine, CA", "Orlando, FL",
    "Pittsburgh, PA", "St. Louis, MO", "Greensboro, NC", "Jersey City, NJ", "Anchorage, AK",
    "Lincoln, NE", "Plano, TX", "Durham, NC", "Buffalo, NY", "Chandler, AZ", "Chula Vista, CA",
    "Toledo, OH", "Madison, WI", "Gilbert, AZ", "Reno, NV", "Fort Wayne, IN", "North Las Vegas, NV",
    "St. Petersburg, FL", "Lubbock, TX", "Irving, TX", "Laredo, TX", "Winston-Salem, NC",
    "Chesapeake, VA", "Glendale, AZ", "Garland, TX", "Scottsdale, AZ", "Norfolk, VA", "Boise, ID",
    "Fremont, CA", "Spokane, WA", "Santa Clarita, CA", "Baton Rouge, LA", "Richmond, VA",
    "Hialeah, FL", "San Bernardino, CA", "Tacoma, WA", "Modesto, CA", "Huntsville, AL",
    "Des Moines, IA", "Yonkers, NY", "Rochester, NY", "Moreno Valley, CA", "Fayetteville, NC",
    "Fontana, CA", "Columbus, GA", "Worcester, MA", "Port St. Lucie, FL", "Little Rock, AR",
    "Augusta, GA", "Oxnard, CA", "Birmingham, AL", "Montgomery, AL", "Frisco, TX", "Amarillo, TX",
    "Salt Lake City, UT", "Grand Rapids, MI", "Huntington Beach, CA", "Overland Park, KS",
    "Glendale, CA", "Tallahassee, FL", "Grand Prairie, TX", "McKinney, TX", "Cape Coral, FL",
    "Sioux Falls, SD", "Peoria, AZ", "Providence, RI", "Vancouver, WA", "Knoxville, TN",
    "Akron, OH", "Shreveport, LA", "Mobile, AL", "Brownsville, TX", "Newport News, VA",
    "Fort Lauderdale, FL", "Chattanooga, TN", "Tempe, AZ", "Oceanside, CA", "Roswell, GA",
    "Rancho Cucamonga, CA", "Ontario, CA", "Santa Rosa, CA", "Elk Grove, CA", "Salem, OR",
    "Pompano Beach, FL", "Springfield, MO", "Springfield, MA", "Corona, CA", "Eugene, OR",
    "Peoria, IL", "Cary, NC", "Pembroke Pines, FL", "Fort Collins, CO", "Lancaster, CA",
    "McAllen, TX", "Palmdale, CA", "Salinas, CA", "Alexandria, VA", "Hayward, CA",
    "Springfield, IL", "Macon, GA", "Kansas City, KS", "Sunnyvale, CA", "Pomona, CA",
    "Paterson, NJ", "Syracuse, NY", "Lakewood, CO", "Hollywood, FL", "Roseville, CA",
    "Miramar, FL", "Clarksville, TN", "Bridgeport, CT", "Joliet, IL", "Surprise, AZ",
    "Naperville, IL", "Mesquite, TX", "Dayton, OH", "Savannah, GA", "Pasadena, TX",
    "Orange, CA", "Fullerton, CA", "Bellevue, WA", "McKinney, TX", "Murfreesboro, TN",
    "Olathe, KS", "Sterling Heights, MI", "Midland, TX", "Waco, TX", "Gainesville, FL",
    "Coral Springs, FL", "Charleston, SC", "Visalia, CA", "Burbank, CA", "Kent, WA",
    "West Valley City, UT", "Lafayette, LA", "Flint, MI", "Auburn, WA", "Everett, WA",
    "Rentz, GA", "Athens, GA", "San Mateo, CA", "San Leandro, CA", "Redwood City, CA",
    "Santa Clara, CA", "Cupertino, CA", "Mountain View, CA", "Palo Alto, CA", "Menlo Park, CA",
    "Los Gatos, CA", "Campbell, CA", "Milpitas, CA", "South San Francisco, CA", "San Bruno, CA",
    "Burlingame, CA", "Foster City, CA", "Daly City, CA", "Emeryville, CA", "Berkeley, CA",
    "Richmond, CA", "Walnut Creek, CA", "Concord, CA", "San Ramon, CA", "Pleasanton, CA",
    "Livermore, CA", "Dublin, CA", "Novato, CA", "San Rafael, CA", "Bothell, WA",
    "Redmond, WA", "Kirkland, WA", "Issaquah, WA", "Sammamish, WA", "Bentonville, AR",
    "Cambridge, MA", "Somerville, MA", "Waltham, MA", "Burlington, MA", "Newton, MA",
    "Ann Arbor, MI", "Madison, WI", "Bloomington, IN", "Boulder, CO", "Hoboken, NJ",
    "Princeton, NJ", "Evanston, IL", "Santa Monica, CA", "Culver City, CA", "Venice, CA",
    "Boca Raton, FL", "West Palm Beach, FL", "Stamford, CT", "Greenwich, CT", "Wilmington, DE",
    "Reston, VA", "Herndon, VA", "Tysons, VA", "Bethesda, MD", "Silver Spring, MD",
    "Hoboken, NJ", "Jersey City, NJ", "Alpharetta, GA", "Sandy Springs, GA", "Dunwoody, GA",
    "San Marcos, TX", "Round Rock, TX", "Cedar Park, TX", "Leander, TX", "Pflugerville, TX",
    "Richardson, TX", "Plano, TX", "Frisco, TX", "Allen, TX", "McKinney, TX", "Coppell, TX",
    "Provo, UT", "Orem, UT", "Lehi, UT", "Sandy, UT", "Draper, UT", "South Jordan, UT",
    "Clearwater, FL", "Sarasota, FL", "Naples, FL", "Pensacola, FL", "Daytona Beach, FL"
]
